### PR TITLE
Media availability UX enhancements

### LINKED ISSUE #160: UX enhancements around availability dates
I believe it's reasonably common for the availability dates to play a large role in the way editors and site administrators want to see their media data from mpx.

This request issue is for a couple of things:

### Availability field formatter

It would be useful to have a summary field formatter, designed to be used with either the available or expired mapped field in Drupal to show at a glance the availability status of a given video, eg.

**Video that is not yet available**
Upcoming 07/21/2020 10:00

**Video that is available until a defined expiry**
Available until 12/31/2020 10:00

**Video that is available indefinately**
Available

**Video that is expired**
Expired on 01/31/2020 10:00

### Availability filter

It's common for editors to want to see just the videos that are available, just the videos that are upcoming or available, and just the videos that are expired. To that end lets add a views filter that will quickly work out the appropriate joins / where clauses for both mapped fields if they are mapped and defined.

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves #160

### CODE REVIEW

**Comment by m4olivei** [comment]
@deviantintegral :wave: hi there. I'm stuck again on the [codeclimate](https://codeclimate.com/github/Lullabot/media_mpx/pull/161) job. It's complaining about the number of constructor arguments. Drupal plugins just have this problem. Other exceptions were made for issues like this in the past, eg. [this one](https://codeclimate.com/github/Lullabot/media_mpx/issues?status%5B%5D=&status%5B%5D=wontfix#issue_5f0f4ea8f3a2ee0001000077). Can I get access to mark exceptions, or do you mind marking these two exceptions?

**Comment by deviantintegral** [comment]
Can you log in via github to code climate? You're an admin on this repo, and it looks like you should have access based on your GitHub permissions: https://docs.codeclimate.com/docs/organization-roles-permissions

I'm totally happy with the feature additions, but may not have time to review. Is there anyone else on your team who can take a look?

**Comment by m4olivei** [comment]
@deviantintegral I am logged in via my Github account, but I don't see the issue drop downs to set status to Won't Fix:

image

According to [the docs](https://docs.codeclimate.com/docs/issues) I should see a drop down where it says "New" after the issue title, but I don't :confused: . Maybe b/c it's my pull request?

With respect to the reviews, no worries, we can review. Do you mind making sure that Matt W (@mattwith) and Amin (@aminnelson) have access to this repo and code climate? Thanks!

**Comment by m4olivei** [comment]
@deviantintegral Reading through https://docs.codeclimate.com/docs/organization-roles-permissions. Do we have team-based or Github-backed authorization? Looks like regardless of which one we have, you still have to grant access on code climate to be able to manage issues (eg. mark as won't fix). I reached out to their support to see if I can get a quick clear answer.

image

**Comment by m4olivei** [comment]
I've got access now! Yay! Code climate issues are now fixed.

**Comment by m4olivei** [comment]
I'm going to merge this now, as @aminnelson approved the same on our fork.

**Comment by deviantintegral** [comment]
@m4olivei FYI you're an admin on this repo so you should have full access to grant others access as needed.

**Pull request merged**
