### PR TITLE
Media type migrations

### PR DESCRIPTION
**Pull request by deviantintegral**
This migrates:

* mpx accounts
* mpx users
* Creates media types for each account
* Migrates media associated with each media type

Run them all with `drush mim --group=media_theplatform_mpx`. By default, this will migrate from data in a 'migrate' database configured in settings.php, just like any other migration.

### CODE REVIEW

**Comment by juampynr** [comment]
@deviantintegral, this is still listed as WIP. Are you still working on it?

**Comment by juampynr** [comment]
@deviantintegral can you fix conflicts in this branch?

**Comment by juampynr** [comment]
Oh wow, I like code climate:

image

I think that I am going to add that to https://github.com/Lullabot/drupal8ci/

**Comment by deviantintegral** [comment]
FYI @juampynr , it's not conflicts, but I've turned on the setting that requires feature branches to be updated with master. You can use the "Update branch" button or merge locally if you'd rather.

**Comment by deviantintegral** [comment]
@juampynr I refactored to simplify the return statements, this PR should be good to review now.

**Pull request merged**
