### PR TITLE
Issue #66 Fix the Url class namespace

### LINKED ISSUE #66: Class 'Lullabot\Mpx\Player\Url' not found in Drupal\media_mpx\Plugin\Field\FieldFormatter\PlayerFormatter->renderIframes()
When rendering a "mpx Video Player" field formatter the following error is triggered:

```
The website encountered an unexpected error. Please try again later.
Error: Class 'Lullabot\Mpx\Player\Url' not found in Drupal\media_mpx\Plugin\Field\FieldFormatter\PlayerFormatter->renderIframes() (line 256 of modules/contrib/media_mpx/src/Plugin/Field/FieldFormatter/PlayerFormatter.php).
Drupal\media_mpx\Plugin\Field\FieldFormatter\PlayerFormatter->renderIframes(Object, Object, Array) (Line: 140)
Drupal\media_mpx\Plugin\Field\FieldFormatter\PlayerFormatter->viewElements(Object, 'en') (Line: 80)
Drupal\Core\Field\FormatterBase->view(Object, 'en') (Line: 262)
Drupal\Core\Entity\Entity\EntityViewDisplay->buildMultiple(Array) (Line: 321)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'full') (Line: 263)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 220)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 665)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

### PR DESCRIPTION
**Pull request by m4olivei**
Resolves #66

### CODE REVIEW

**Comment by deviantintegral** [comment]
Looks like this is https://www.drupal.org/project/drupal/issues/2921661

So Docker Hub's auto rebuild feature has been randomly not triggering. That means the current container is pointing to 8.5.6, not 8.5.7 that fixes this bug. I'll force a rebuild.

```
$ docker pull andrewberry/drupal_tests:0.3.4 && docker run --rm -it andrewberry/drupal_tests:0.3.4 bash -c 'export' | grep DRUPAL_VERSION                                                                                                                                      
0.3.4: Pulling from andrewberry/drupal_tests
Digest: sha256:7cb2ea791f219c178936d0b5716717be92dbab1fffa0fb27aa1e82ae9d5e57fc
Status: Image is up to date for andrewberry/drupal_tests:0.3.4
declare -x DRUPAL_VERSION="8.5.6"
```

**Comment by deviantintegral** [comment]
@m4olivei I've upgraded the test container to 8.5.7, but it looks like we still have a bug with an exception in the JS tests. Master passes for me.

I'm pretty sure on our current site we're actually pointing to https://github.com/Lullabot/mpx-php/pull/141 which includes a set of other changes: https://github.com/Lullabot/mpx-php/compare/0.6.2...master

How about we finish that PR, create a new tag ,and then we can update composer.json here?

**Comment by m4olivei** [comment]
@deviantintegral Tests pass! This should be good to go now.

**Review by deviantintegral — APPROVED** [review]
Excellent, thanks!

**Pull request merged**
